import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {launchProbeBrowser} from '../../../../scripts/lib/probeBrowser.mjs';
import {CLIENT_NEXT_BASE_URL} from '../../../../scripts/lib/probeEndpoints.mjs';
test('Blocking UI keeps server and local lists separate across dialogs and reload',{timeout:90000},async()=>{
 const {browser,page}=await launchProbeBrowser();
 try{
 await page.setViewportSize({width:1200,height:900});await page.goto(CLIENT_NEXT_BASE_URL);
 await page.waitForFunction(()=>document.querySelector('output')?.textContent?.includes('runtime: running'));
  await page.evaluate(async()=>{
   localStorage.removeItem('sro:v1150:chatting-blocks:1');
   const entry=Array.from(document.scripts).find(s=>s.src&&new URL(s.src).pathname==='/src/bootstrap.ts');
   const {runtime}=await import(entry.src);runtime.dispose();
   const {createUi}=await import('/src/engine/runtime/ui/ui.ts'),{createRenderer}=await import('/src/engine/runtime/renderer/renderer.ts'),{createPlatform}=await import('/src/engine/runtime/platform/platform.ts');
   const jobs=new Map(),requests=[],commands=[],renderer=createRenderer(document.querySelector('canvas'));let serial=0,scene=null;
   const assets={available:()=>Math.max(0,32-jobs.size),request(url,limit,kind){const id=++serial;jobs.set(id,null);requests.push(url);fetch(url).then(async r=>{if(!r.ok)throw Error(r.status+' '+url);const result=kind==='png'?{kind:'image',image:await createImageBitmap(await r.blob())}:{kind:'bytes',buffer:await r.arrayBuffer()};if(jobs.has(id))jobs.set(id,result);else if(result.kind==='image')result.image.close();}).catch(e=>{if(jobs.has(id))jobs.set(id,{kind:'error',error:String(e)});});return id;},take(id){const result=jobs.get(id);if(result)jobs.delete(id);return result;},cancel(id){const result=jobs.get(id);if(result?.kind==='image')result.image.close();jobs.delete(id);}};
   let platform;const ui=createUi(assets,c=>commands.push(c),s=>{scene=s;renderer.setUi(s);},(id,image)=>renderer.setUiTexture(id,image),location.origin,'http://fixture.invalid',()=>{},()=>{},()=>1,()=>0,value=>platform.saveGameOptions(value),undefined,undefined,undefined,undefined,value=>platform.saveChatBlocks(value));
   platform=createPlatform(document.querySelector('canvas'),document.querySelector('output'),()=>{},()=>{},()=>{},ui.event,ui.blocks);
   const state={session:{phase:'world',revision:1,character:'Fixture',characters:[{id:1,name:'Fixture',level:1,maxHp:200,maxMp:200}]},gameplay:{localGid:1,inventory:[],inventorySlotCount:45,equipmentSlotCount:13,vitals:[{gid:1,hp:200,mp:200}],casts:[]},entities:[],width:1200,height:900,worldReady:true};
   window.flagFixture={ui,renderer,platform,state,requests,commands,get scene(){return scene;},get pending(){return jobs.size;},restorePlatform(){platform.dispose();platform=createPlatform(document.querySelector('canvas'),document.querySelector('output'),()=>{},()=>{},()=>{},ui.event,ui.blocks);this.platform=platform;},draw(){const semantic=ui.step({...state},performance.now());if(semantic)platform.presentUi(semantic);renderer.frame({width:state.width,height:state.height});}};
   state.gameplay.chat={blocked:['ServerName'],blockPending:false,lines:[],feedback:[]};flagFixture.draw();
  });
  await page.waitForFunction(()=>{flagFixture.draw();return flagFixture.pending===0;},null,{timeout:20000});
  await page.evaluate(()=>{flagFixture.ui.event({kind:'activate',id:'open-window:Blocking'});flagFixture.draw();});
  await page.waitForFunction(()=>{flagFixture.draw();return !!document.querySelector('[data-ui-id="blocking-add"]')&&!flagFixture.ui.stats().windowMissing.length;},null,{timeout:25000});
  assert.equal(await page.locator('[data-ui-id="blocking-row:0"]').getAttribute('aria-label'),'ServerName');
  await page.locator('[data-ui-id="blocking-tab:1"]').click();await page.evaluate(()=>flagFixture.draw());
  assert.equal(await page.locator('[data-ui-id="blocking-row:0"]').count(),0);
  await page.locator('[data-ui-id="blocking-add"]').click();
  await page.waitForFunction(()=>{flagFixture.draw();return !!document.querySelector('[data-ui-id="blocking-name"]');});
  await page.locator('[data-ui-id="blocking-name"]').fill('LocalName');await page.evaluate(()=>flagFixture.draw());
  await mkdir('temp/artifacts/blocking',{recursive:true});await page.screenshot({path:'temp/artifacts/blocking/add.png'});
  await page.keyboard.press('Enter');await page.evaluate(()=>flagFixture.draw());
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('sro:v1150:chatting-blocks:1'))),['LocalName']);
  assert.equal(await page.locator('[data-ui-id="blocking-row:0"]').getAttribute('aria-label'),'LocalName');
  await page.locator('[data-ui-id="blocking-row:0"]').click();await page.evaluate(()=>flagFixture.draw());
  await page.locator('[data-ui-id="blocking-remove"]').click();await page.evaluate(()=>flagFixture.draw());
  await page.keyboard.press('Escape');await page.evaluate(()=>flagFixture.draw());
  assert.equal(await page.locator('[data-ui-id="blocking-row:0"]').count(),1);
  await page.locator('[data-ui-id="blocking-remove"]').click();await page.evaluate(()=>flagFixture.draw());
  await page.locator('[data-ui-id="blocking-ok"]').click();await page.evaluate(()=>flagFixture.draw());
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('sro:v1150:chatting-blocks:1'))),[]);
  await page.locator('[data-ui-id="blocking-tab:0"]').click();await page.evaluate(()=>flagFixture.draw());
  await page.locator('[data-ui-id="blocking-add"]').click();await page.waitForFunction(()=>{flagFixture.draw();return !!document.querySelector('[data-ui-id="blocking-name"]');});
  await page.locator('[data-ui-id="blocking-name"]').fill('Peer');await page.evaluate(()=>flagFixture.draw());await page.keyboard.press('Enter');await page.evaluate(()=>flagFixture.draw());
  assert.deepEqual(await page.evaluate(()=>flagFixture.commands.at(-1)),{kind:'gameplay',command:{kind:'whisper-block',name:'Peer',blocked:true}});
  assert.equal(await page.locator('[data-ui-id="blocking-row:0"]').getAttribute('aria-label'),'ServerName');
  assert.equal(await page.locator('[data-ui-id="blocking-row:1"]').count(),0,'No optimistic server mutation');
  await page.evaluate(()=>{const f=flagFixture;f.state.gameplay={...f.state.gameplay,revision:5,chat:{...f.state.gameplay.chat,blockPending:true}};f.draw();});
  assert.equal(await page.locator('[data-ui-id="blocking-add"]').isDisabled(),true);
  await page.locator('[data-ui-id="blocking-tab:1"]').click();await page.evaluate(()=>flagFixture.draw());
  assert.equal(await page.locator('[data-ui-id="blocking-add"]').isDisabled(),false,'A pending server request cannot lock the local list');
  await page.evaluate(()=>{const f=flagFixture;f.platform.saveChatBlocks(Array.from({length:22},(_,i)=>'Local'+i));f.ui.event({kind:'chat-blocks',value:[]});f.restorePlatform();f.draw();});
  assert.equal(await page.locator('[data-ui-id^="blocking-row:"]').count(),10);
  assert.equal(await page.locator('[data-ui-id="blocking-row:0"]').getAttribute('aria-label'),'Local0','Fresh platform restores the saved preference');
  await page.evaluate(()=>{flagFixture.ui.event({kind:'drag',id:'blocking-thumb',dx:0,dy:185});flagFixture.draw();});
  assert.equal(await page.locator('[data-ui-id="blocking-row:21"]').getAttribute('aria-label'),'Local21','No whisper-style twenty-name cap on local blocks');
  await page.locator('[data-ui-id="blocking-add"]').click();await page.evaluate(()=>flagFixture.draw());
  await page.locator('[data-ui-id="blocking-name"]').fill('[GM]');await page.evaluate(()=>flagFixture.draw());await page.keyboard.press('Enter');await page.evaluate(()=>flagFixture.draw());
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sro:v1150:chatting-blocks:1')).length),22);
  await page.locator('[data-ui-id="blocking-add"]').click();await page.evaluate(()=>flagFixture.draw());
  await page.locator('[data-ui-id="blocking-name"]').fill('Local0');await page.evaluate(()=>flagFixture.draw());await page.keyboard.press('Enter');await page.evaluate(()=>flagFixture.draw());
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sro:v1150:chatting-blocks:1')).length),22,'Duplicate must not append');
  await page.screenshot({path:'temp/artifacts/blocking/list.png'});

  assert.deepEqual(await page.evaluate(()=>flagFixture.ui.stats().failed),[]);assert.equal(await page.evaluate(()=>flagFixture.renderer.error()),null);
  await page.evaluate(()=>{flagFixture.ui.dispose();flagFixture.platform.dispose();flagFixture.renderer.dispose();});
  await page.reload();await page.waitForFunction(()=>document.querySelector('output')?.textContent?.includes('runtime: running'));
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sro:v1150:chatting-blocks:1')).length),22,'Browser refresh retains the local list');
 }finally{await browser.close();}
});
