import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {launchProbeBrowser} from '../../../../scripts/lib/probeBrowser.mjs';
import {CLIENT_NEXT_BASE_URL} from '../../../../scripts/lib/probeEndpoints.mjs';
import {resolveProbeCredentials} from '../../../../scripts/lib/probeSession.mjs';
import {assertCharacterAllowed} from '../../../../scripts/lib/probeCharacter.mjs';
import {holdProbeRuntime} from './helpers/hold-runtime.mjs';
test('authenticated reset/rebirth uses the native loading event and completes a fresh ready handshake',{timeout:180000},async t=>{
 const character=assertCharacterAllowed('asd2',{context:'travel loading fixture'}),{browser,page}=await launchProbeBrowser({viewport:{width:1024,height:768}});t.after(()=>browser.close());await holdProbeRuntime(page);
 await mkdir('temp/artifacts/travel',{recursive:true});const control=id=>page.locator('[data-ui-id="'+id+'"]');let socket,isolated=false,recording=true;const initial=[],outbound=[],evidence=[],failures=[];page.on('requestfailed',request=>failures.push({path:new URL(request.url()).pathname,error:request.failure()?.errorText}));page.on('response',response=>{if(response.status()>=400)failures.push({path:new URL(response.url()).pathname,status:response.status()});});
 await page.addInitScript(()=>{window.__travel={events:[],ready:0};const Base=Worker;window.Worker=class extends Base{postMessage(data,...args){if(data.kind==='session'&&data.command?.kind==='world-ready')window.__travel.ready++;return super.postMessage(data,...args);}constructor(...args){super(...args);this.addEventListener('message',({data})=>{if(data.kind==='world')for(const event of data.batch.events){if(event.kind==='travel')window.__travel.events.push(event.travel);if(event.kind==='gameplay')window.__travel.game=event.state;}if(data.kind==='session')window.__travel.session={phase:data.state.phase,error:data.state.error};if(data.kind==='failure')window.__travel.error=data.message;});}};});
 await page.route('**/character/list',async route=>{const response=await route.fetch(),body=await response.json();await route.fulfill({response,json:{...body,characters:body.characters.filter(row=>row.name===character)}});});
 try{
 console.info('travel: authenticated boot');await page.goto(CLIENT_NEXT_BASE_URL+'?diagnostics');await control('frontend:reveal').click({timeout:30000});await page.waitForFunction(()=>document.querySelector('[data-ui-id="login"]')&&!document.querySelector('[data-ui-id="login"]').disabled);
 const {loginId,loginPassword}=resolveProbeCredentials();await control('account').fill(loginId);await control('password').fill(loginPassword);await control('password').press('Enter');await control('frontend:create').waitFor({timeout:40000});socket=page.workers().find(worker=>worker.url().includes('/simulation/worker/entry.ts'));assert.ok(socket);await socket.evaluate(()=>{
 const Base=WebSocket;globalThis.__travelWire={initial:[],outbound:[],isolated:false};
 globalThis.WebSocket=class extends Base{constructor(...args){super(...args);globalThis.__travelSocket=this;}set onmessage(handler){this.handler=handler;super.onmessage=event=>{const r=globalThis.__travelWire,bytes=new Uint8Array(event.data),op=bytes[0]|bytes[1]<<8;if(!r.isolated||op===3){if([7,0x32a6,0x30cb,0x3417,0x330a].includes(op))r.initial.push([...bytes]);handler.call(this,event);}};}get onmessage(){return this.handler;}send(bytes){globalThis.__travelWire.outbound.push(new DataView(bytes.buffer??bytes,bytes.byteOffset??0,2).getUint16(0,true));if(!globalThis.__travelWire.isolated||new DataView(bytes.buffer??bytes,bytes.byteOffset??0,2).getUint16(0,true)===4)super.send(bytes);}inject(bytes){this.handler.call(this,{data:new Uint8Array(bytes).buffer});}};
});await page.mouse.click(505,430);await control('enter').waitFor();await page.waitForFunction(()=>!document.querySelector('[data-ui-id="enter"]')?.disabled);await control('enter').click();await page.waitForFunction(()=>window.__travel.ready===1,null,{timeout:60000});recording=false;isolated=true;socket=page.workers().find(worker=>worker.url().includes('/simulation/worker/entry.ts'));assert.ok(socket);await socket.evaluate(()=>{globalThis.__travelWire.isolated=true;});initial.push(...await socket.evaluate(()=>globalThis.__travelWire.initial.map(row=>row)));for(let i=0;i<initial.length;i++)initial[i]=Buffer.from(initial[i]);
 const game=await page.evaluate(()=>window.__travel.game);assert.ok(game.localGid);assert.ok(initial.some(row=>row.readUInt16LE()===7));
 function send(op,payload){const bytes=Buffer.alloc(2+payload.length);bytes.writeUInt16LE(op);Buffer.from(payload).copy(bytes,2);return socket.evaluate(bytes=>globalThis.__travelSocket.inject(bytes),[...bytes]);}
 for(const [index,opcode] of [0x3369,0x366a].entries()){
 console.info('travel: reset '+opcode.toString(16));const death=Buffer.alloc(6);death.writeUInt32LE(game.localGid);death[5]=2;const region=Buffer.alloc(2);region.writeUInt16LE(game.pose.regionId);const eventCount=await page.evaluate(()=>window.__travel.events.length);const acks=await socket.evaluate(()=>globalThis.__travelWire.outbound.filter(op=>op===0x36dd).length);const reset=Buffer.alloc(4);reset.writeUInt16LE(opcode);region.copy(reset,2);const dead=Buffer.alloc(8);dead.writeUInt16LE(0x3122);death.copy(dead,2);await socket.evaluate(frames=>{for(const frame of frames)globalThis.__travelSocket.inject(frame);},[dead,reset,...initial].map(frame=>[...frame]));
 await page.waitForFunction(n=>window.__travel.events.length>=n,eventCount+1);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const png=await page.screenshot({path:'temp/artifacts/travel/rebirth-'+opcode.toString(16)+'.png'});
 const error=await page.evaluate(async png=>{const c=document.createElement('canvas');c.width=1024;c.height=768;const ctx=c.getContext('2d'),points=[[800,200],[400,350],[900,400],[600,200]];async function sample(url){const b=await createImageBitmap(await(await fetch(url)).blob());ctx.fillStyle='black';ctx.fillRect(0,0,1024,768);ctx.drawImage(b,0,0,1024,768);b.close();return points.flatMap(([x,y])=>[...ctx.getImageData(x,y,1,1).data].slice(0,3));}const a=await sample('data:image/png;base64,'+png),b=await sample('/assets/images/Media_extracted/interface/loading/loading_rebirth.png');return Math.max(...a.map((v,i)=>Math.abs(v-b[i])));},png.toString('base64'));
 assert.ok(error<=3,'rebirth raster '+error);assert.equal(await socket.evaluate(()=>globalThis.__travelWire.outbound.filter(op=>op===0x36dd).length),acks+(opcode===0x3369?1:0));
 await page.waitForFunction(n=>window.__travel.ready===n,index+2,{timeout:60000});assert.equal(await page.evaluate(()=>window.__travel.error),undefined);evidence.push({opcode,mode:1,region:game.pose.regionId,pixelError:error,ready:await page.evaluate(()=>window.__travel.ready)});
 }
 }finally{await page.screenshot({path:'temp/artifacts/travel/final.png'});await writeFile('temp/artifacts/travel/reset.json',JSON.stringify({evidence,failures,outbound:socket?await socket.evaluate(()=>globalThis.__travelWire.outbound).catch(()=>[]):[],events:await page.evaluate(()=>window.__travel)},null,2));}
});
