"""Project recovered hive caps by natural nest identity, never wire object IDs."""
import argparse
import hashlib
import json
from collections import defaultdict
from pathlib import Path


def project(rows, world_codes):
    groups = defaultdict(list)
    policies = {}
    for row in rows:
        hive = row.get('hive')
        if hive:
            world_code = world_codes[hive['GameWorldID']]
            policy = (hive['btKeepMonsterCountType'], hive['fMonsterCountPerPC'], hive['dwSpawnSpeedIncreaseRate'], hive['dwMaxIncreaseRate'], world_code)
            if policy[0] == 1 and hive['GameWorldID'] != 1:
                raise ValueError('density world needs an explicit cross-version world join')
            if row['dwHiveID'] in policies and policies[row['dwHiveID']] != policy:
                raise ValueError('inconsistent hive density policy')
            policies[row['dwHiveID']] = policy
            key = (row['codename'], row['regionId'], row['fLocalPosX'], row['fLocalPosY'], row['fLocalPosZ'])
            groups[row['dwHiveID']].append((key, hive['dwOverwriteMaxTotalCount'], row['dwNestID']))
    output = []
    for hive_id, members in groups.items():
        caps = {cap for _, cap, _ in members}
        if len(caps) != 1:
            raise ValueError('inconsistent hive limit')
        keys = sorted({key for key, _, _ in members})
        identity = hashlib.sha256(json.dumps(keys, separators=(',', ':')).encode()).hexdigest()
        # GameServer 55E7C0 keys the hive's nest map by dwNestID and 55E6EB
        # copies that map into the vector 55EC10/55EEC0 iterate, so native
        # hive order is ascending nest id. Only the rank crosses versions.
        first_id = {}
        for key, _, nest_id in members:
            first_id[key] = min(nest_id, first_id.get(key, nest_id))
        ordinal = {key: rank for rank, key in enumerate(sorted(keys, key=lambda k: (first_id[k], k)))}
        for code, region, x, y, z in keys:
            suffix = '\t'.join(str(v) for v in policies[hive_id])
            output.append(f'{code}\t{region}\t{x:.6f}\t{y:.6f}\t{z:.6f}\t{identity}\t{next(iter(caps))}\t{ordinal[(code, region, x, y, z)]}\t{suffix}')
    return '\n'.join(sorted(output))+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('--worlds', type=Path, required=True, help='source-version gameworlddata, joined by code name')
    args = parser.parse_args()
    if args.input.resolve() == args.output.resolve():
        parser.error('output must not overwrite source evidence')
    raw = args.input.read_bytes()
    world_raw = args.worlds.read_bytes()
    world_text = world_raw.decode('utf-16' if world_raw[:2] in (b'\xff\xfe', b'\xfe\xff') else 'utf-8-sig')
    world_codes = {}
    for line in world_text.splitlines():
        fields = line.split('\t')
        if len(fields) < 2 or not fields[0].isdigit():
            continue
        world_id = int(fields[0])
        if world_id in world_codes:
            raise ValueError('duplicate source world identity')
        world_codes[world_id] = fields[1]
    header = '# Generated by scripts/analysis/project_hive_caps.py\n'
    header += '# Source JSON SHA256: '+hashlib.sha256(raw).hexdigest()+'\n'
    header += '# Source world catalog SHA256: '+hashlib.sha256(world_raw).hexdigest()+'\n'
    header += '# codename\tregion\tx\ty\tz\tnatural-membership-sha256\tmax-live\thive-order\tkeep-count-type\tmonsters-per-PC\trate-step\trate-max\tworld-code\n'
    args.output.write_text(header+project(json.loads(raw), world_codes), encoding='utf-8', newline='\n')
