package simulation

import (
	"bytes"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"opensro.online/server/internal/game/item/wire"
)

// The parity suite replays golden vectors generated by the (retired) Node
// reference implementation (testdata/gen_parity_vectors.mjs, corrected copies
// of the deleted rebuild/apps/launcher-api/src/server.mjs). Positions compare within
// floatTolerance (identical float64 op sequences, but Math.hypot/atan2 may
// differ from Go's libm by ulps); every wire byte and integer field compares
// EXACT.
//
// WHAT THIS SUITE IS AND IS NOT. It is a DRIFT detector: it catches the Go port
// silently diverging from the behaviour the Node prototype implemented. It is
// NOT a native oracle - server.mjs was our own prototype, not a captured retail
// stream - so where the prototype provably disagrees with the v1.150 client
// binary, the binary wins and the fixture gets regenerated with the reason
// recorded. Native 853550/8535A0 require a pi/2 offset between model yaw and
// wire bearing. Movement/patrol vectors were corrected on 2026-09-12; the
// generator documents this intentional difference from the retired prototype.
const floatTolerance = 1e-9

type jsSpawn struct {
	RegionID uint16  `json:"regionId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
	Angle    uint16  `json:"angle"`
}

func (s jsSpawn) spawn() Spawn {
	return Spawn(s)
}

type jsSegment struct {
	From        jsSpawn `json:"from"`
	StartedAtMs int64   `json:"startedAtMs"`
	ArrivesAtMs int64   `json:"arrivesAtMs"`
}

func (s *jsSegment) segment() *MoveSegment {
	if s == nil {
		return nil
	}
	return &MoveSegment{From: s.From.spawn(), StartedAtMs: s.StartedAtMs, ArrivesAtMs: s.ArrivesAtMs}
}

type jsWorld struct {
	Spawn                jsSpawn    `json:"spawn"`
	MoveSegment          *jsSegment `json:"moveSegment"`
	MovementMode         uint8      `json:"movementMode"`
	SpawnSet             bool       `json:"spawnSet"`
	MovementSourceSeeded bool       `json:"movementSourceSeeded"`
}

func (w jsWorld) world() WorldState {
	return WorldState{
		Spawn:                w.Spawn.spawn(),
		MoveSegment:          w.MoveSegment.segment(),
		MovementMode:         w.MovementMode,
		SpawnSet:             w.SpawnSet,
		MovementSourceSeeded: w.MovementSourceSeeded,
	}
}

type jsMovement struct {
	Mode     uint8   `json:"mode"`
	RegionID uint16  `json:"regionId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
}

func (m jsMovement) movement() MovementRequest {
	return MovementRequest{Mode: m.Mode, RegionID: m.RegionID, X: m.X, Y: m.Y, Z: m.Z}
}

type jsSource struct {
	RegionID uint16  `json:"regionId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
}

type parityVectors struct {
	LiveSpawn []struct {
		Name     string  `json:"name"`
		World    jsWorld `json:"world"`
		NowMs    int64   `json:"nowMs"`
		Expected jsSpawn `json:"expected"`
	} `json:"liveSpawn"`
	MoveSegmentForTravel []struct {
		Name         string     `json:"name"`
		LiveFrom     jsSpawn    `json:"liveFrom"`
		NextSpawn    jsSpawn    `json:"nextSpawn"`
		MovementMode uint8      `json:"movementMode"`
		StartedAtMs  int64      `json:"startedAtMs"`
		Expected     *jsSegment `json:"expected"`
		Distance     float64    `json:"distance"`
	} `json:"moveSegmentForTravel"`
	Heading []struct {
		Name     string  `json:"name"`
		From     jsSpawn `json:"from"`
		To       jsSpawn `json:"to"`
		Expected *int    `json:"expected"`
	} `json:"heading"`
	WorldDistance []struct {
		Name     string  `json:"name"`
		A        jsSpawn `json:"a"`
		B        jsSpawn `json:"b"`
		Expected float64 `json:"expected"`
	} `json:"worldDistance"`
	MovementAck []struct {
		Name          string     `json:"name"`
		ObjectID      uint32     `json:"objectId"`
		Movement      jsMovement `json:"movement"`
		Source        *jsSource  `json:"source"`
		ExpectedBytes []byte     `json:"expectedBytes"`
	} `json:"movementAck"`
	ApplyMove struct {
		ObjectID     uint32  `json:"objectId"`
		InitialWorld jsWorld `json:"initialWorld"`
		Steps        []struct {
			Action       string     `json:"action"`
			Name         string     `json:"name"`
			AtMs         int64      `json:"atMs"`
			Movement     jsMovement `json:"movement"`
			MovementMode uint8      `json:"movementMode"`
			Expect       struct {
				AckBytes       []byte     `json:"ackBytes"`
				SourceIncluded bool       `json:"sourceIncluded"`
				LiveBefore     jsSpawn    `json:"liveBefore"`
				Spawn          jsSpawn    `json:"spawn"`
				Segment        *jsSegment `json:"segment"`
				Live           jsSpawn    `json:"live"`
			} `json:"expect"`
		} `json:"steps"`
	} `json:"applyMove"`
	Patrol []struct {
		AnchorName string  `json:"anchorName"`
		Anchor     jsSpawn `json:"anchor"`
		Ticks      []struct {
			Tick     int64 `json:"tick"`
			Expected struct {
				RegionID    uint16  `json:"regionId"`
				X           float64 `json:"x"`
				Y           float64 `json:"y"`
				Z           float64 `json:"z"`
				HeadingWord uint16  `json:"headingWord"`
			} `json:"expected"`
		} `json:"ticks"`
	} `json:"patrol"`
	NpcWire struct {
		CreateRow []struct {
			Npc struct {
				ObjectID uint32 `json:"objectId"`
				RefObjID uint32 `json:"refObjId"`
				TidWord  uint16 `json:"tidWord"`
				Codename string `json:"codename"`
				Name     string `json:"name"`
			} `json:"npc"`
			Anchor        jsSpawn `json:"anchor"`
			ExpectedBytes []byte  `json:"expectedBytes"`
		} `json:"createRow"`
		MovePayloads []struct {
			Tick          int64   `json:"tick"`
			Anchor        jsSpawn `json:"anchor"`
			ExpectedBytes []byte  `json:"expectedBytes"`
		} `json:"movePayloads"`
		CorrectionPayloads []struct {
			Tick          int64   `json:"tick"`
			Anchor        jsSpawn `json:"anchor"`
			ExpectedBytes []byte  `json:"expectedBytes"`
		} `json:"correctionPayloads"`
		StatePayloads []struct {
			Tick          int64  `json:"tick"`
			ExpectedBytes []byte `json:"expectedBytes"`
		} `json:"statePayloads"`
		LifePayloads []struct {
			Tick          int64  `json:"tick"`
			ExpectedBytes []byte `json:"expectedBytes"`
		} `json:"lifePayloads"`
		DespawnPayloads []struct {
			Index         int    `json:"index"`
			ExpectedBytes []byte `json:"expectedBytes"`
		} `json:"despawnPayloads"`
	} `json:"npcWire"`
	GameReady struct {
		GameTimeBytes []byte `json:"gameTimeBytes"`
		Vitals        []struct {
			ObjectID      uint32 `json:"objectId"`
			CurrentHP     uint32 `json:"currentHp"`
			CurrentMP     uint32 `json:"currentMp"`
			ExpectedBytes []byte `json:"expectedBytes"`
		} `json:"vitals"`
	} `json:"gameReady"`
}

func loadParityVectors(t *testing.T) parityVectors {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "movement_parity.json"))
	if err != nil {
		t.Fatalf("reading parity vectors (regenerate with `node testdata/gen_parity_vectors.mjs`): %v", err)
	}
	var vectors parityVectors
	if err := json.Unmarshal(raw, &vectors); err != nil {
		t.Fatalf("decoding parity vectors: %v", err)
	}
	return vectors
}

func closeEnough(got, want float64) bool {
	if got == want {
		return true
	}
	diff := math.Abs(got - want)
	scale := math.Max(math.Abs(got), math.Abs(want))
	return diff <= floatTolerance || diff <= floatTolerance*scale
}

func assertSpawn(t *testing.T, name string, got Spawn, want jsSpawn) {
	t.Helper()
	if got.RegionID != want.RegionID {
		t.Errorf("%s: regionId = %d (0x%04X), want %d (0x%04X)", name, got.RegionID, got.RegionID, want.RegionID, want.RegionID)
	}
	if !closeEnough(got.X, want.X) {
		t.Errorf("%s: x = %v, want %v", name, got.X, want.X)
	}
	if !closeEnough(got.Y, want.Y) {
		t.Errorf("%s: y = %v, want %v", name, got.Y, want.Y)
	}
	if !closeEnough(got.Z, want.Z) {
		t.Errorf("%s: z = %v, want %v", name, got.Z, want.Z)
	}
	if got.Angle != want.Angle {
		t.Errorf("%s: angle = %d, want %d", name, got.Angle, want.Angle)
	}
}

func assertSegment(t *testing.T, name string, got *MoveSegment, want *jsSegment) {
	t.Helper()
	if want == nil {
		if got != nil {
			t.Errorf("%s: segment = %+v, want nil (zero-length hop must clear the live plane)", name, got)
		}
		return
	}
	if got == nil {
		t.Errorf("%s: segment = nil, want %+v", name, want)
		return
	}
	assertSpawn(t, name+".from", got.From, want.From)
	if got.StartedAtMs != want.StartedAtMs {
		t.Errorf("%s: startedAtMs = %d, want %d", name, got.StartedAtMs, want.StartedAtMs)
	}
	if got.ArrivesAtMs != want.ArrivesAtMs {
		t.Errorf("%s: arrivesAtMs = %d, want %d (travel-time ceil must match)", name, got.ArrivesAtMs, want.ArrivesAtMs)
	}
}

func TestParityLiveSpawn(t *testing.T) {
	vectors := loadParityVectors(t)
	if len(vectors.LiveSpawn) == 0 {
		t.Fatal("no liveSpawn vectors")
	}
	for _, tc := range vectors.LiveSpawn {
		got := tc.World.world().LiveSpawnAt(tc.NowMs)
		assertSpawn(t, tc.Name, got, tc.Expected)
	}
}

func TestParityMoveSegmentForTravel(t *testing.T) {
	vectors := loadParityVectors(t)
	for _, tc := range vectors.MoveSegmentForTravel {
		gotDistance := WorldDistance2D(tc.LiveFrom.spawn(), tc.NextSpawn.spawn())
		if !closeEnough(gotDistance, tc.Distance) {
			t.Errorf("%s: distance = %v, want %v", tc.Name, gotDistance, tc.Distance)
		}
		got := MoveSegmentForTravel(tc.LiveFrom.spawn(), tc.NextSpawn.spawn(), tc.MovementMode, tc.StartedAtMs)
		assertSegment(t, tc.Name, got, tc.Expected)
	}
}

func TestParityHeading(t *testing.T) {
	vectors := loadParityVectors(t)
	for _, tc := range vectors.Heading {
		got, ok := HeadingFromMovement(tc.From.spawn(), tc.To.spawn())
		if tc.Expected == nil {
			if ok {
				t.Errorf("%s: heading = %d, want degenerate (undefined)", tc.Name, got)
			}
			continue
		}
		if !ok {
			t.Errorf("%s: heading degenerate, want %d", tc.Name, *tc.Expected)
			continue
		}
		if int(got) != *tc.Expected {
			t.Errorf("%s: heading = %d, want %d", tc.Name, got, *tc.Expected)
		}
	}
}

func TestParityWorldDistance(t *testing.T) {
	vectors := loadParityVectors(t)
	for _, tc := range vectors.WorldDistance {
		got := WorldDistance2D(tc.A.spawn(), tc.B.spawn())
		if !closeEnough(got, tc.Expected) {
			t.Errorf("%s: distance = %v, want %v", tc.Name, got, tc.Expected)
		}
	}
}

func TestParityMovementAck(t *testing.T) {
	vectors := loadParityVectors(t)
	for _, tc := range vectors.MovementAck {
		var source *MovementSource
		if tc.Source != nil {
			source = &MovementSource{RegionID: tc.Source.RegionID, X: tc.Source.X, Y: tc.Source.Y, Z: tc.Source.Z}
		}
		got := BuildMovementAckPayload(tc.ObjectID, tc.Movement.movement(), source)
		if !bytes.Equal(got, tc.ExpectedBytes) {
			t.Errorf("%s: ack payload\n got % X\nwant % X", tc.Name, got, tc.ExpectedBytes)
		}
	}
}

// TestParityApplyMove replays the reference resteer chain end-to-end. This is
// the bug-D no-regression oracle: the mid-flight probes assert the live plane
// (where a drop would land) against the interpolated point, and the move
// steps assert the resteer departure equals the previous segment's live
// point - never the goal.
func TestParityApplyMove(t *testing.T) {
	vectors := loadParityVectors(t)
	world := vectors.ApplyMove.InitialWorld.world()
	objectID := vectors.ApplyMove.ObjectID
	if len(vectors.ApplyMove.Steps) == 0 {
		t.Fatal("no applyMove steps")
	}

	for _, step := range vectors.ApplyMove.Steps {
		switch step.Action {
		case "move":
			result := ApplyMove(&world, objectID, step.Movement.movement(), step.MovementMode, step.AtMs)
			if !bytes.Equal(result.AckPayload, step.Expect.AckBytes) {
				t.Errorf("%s: ack payload\n got % X\nwant % X", step.Name, result.AckPayload, step.Expect.AckBytes)
			}
			if result.SourceIncluded != step.Expect.SourceIncluded {
				t.Errorf("%s: sourceIncluded = %v, want %v", step.Name, result.SourceIncluded, step.Expect.SourceIncluded)
			}
			assertSpawn(t, step.Name+".liveBefore", result.LiveBefore, step.Expect.LiveBefore)
			assertSpawn(t, step.Name+".spawn", world.Spawn, step.Expect.Spawn)
			assertSegment(t, step.Name+".segment", world.MoveSegment, step.Expect.Segment)
		case "probeLive":
			got := world.LiveSpawnAt(step.AtMs)
			assertSpawn(t, step.Name, got, step.Expect.Live)
			// The heart of bug D: while a segment is in flight, the live
			// plane must differ from the goal plane.
			if seg := world.MoveSegment; seg.Valid() && step.AtMs < seg.ArrivesAtMs && step.AtMs > seg.StartedAtMs {
				if got.RegionID == world.Spawn.RegionID && got.X == world.Spawn.X && got.Z == world.Spawn.Z {
					t.Errorf("%s: mid-flight live position equals the move goal - bug D regressed", step.Name)
				}
			}
		default:
			t.Fatalf("unknown step action %q", step.Action)
		}
	}
}

func TestParityPatrol(t *testing.T) {
	vectors := loadParityVectors(t)
	for _, anchorCase := range vectors.Patrol {
		anchor := anchorCase.Anchor.spawn()
		for _, tickCase := range anchorCase.Ticks {
			got := ComputeNpcPatrolState(anchor, tickCase.Tick)
			name := anchorCase.AnchorName
			if got.RegionID != tickCase.Expected.RegionID {
				t.Errorf("%s tick %d: regionId = %d, want %d", name, tickCase.Tick, got.RegionID, tickCase.Expected.RegionID)
			}
			if !closeEnough(got.X, tickCase.Expected.X) || !closeEnough(got.Y, tickCase.Expected.Y) || !closeEnough(got.Z, tickCase.Expected.Z) {
				t.Errorf("%s tick %d: pose = (%v, %v, %v), want (%v, %v, %v)",
					name, tickCase.Tick, got.X, got.Y, got.Z, tickCase.Expected.X, tickCase.Expected.Y, tickCase.Expected.Z)
			}
			if got.HeadingWord != tickCase.Expected.HeadingWord {
				t.Errorf("%s tick %d: headingWord = %d, want %d", name, tickCase.Tick, got.HeadingWord, tickCase.Expected.HeadingWord)
			}
		}
	}
}

func TestParityNpcWire(t *testing.T) {
	vectors := loadParityVectors(t)

	for _, tc := range vectors.NpcWire.CreateRow {
		npc := NpcDef{ObjectID: tc.Npc.ObjectID, RefObjID: tc.Npc.RefObjID, TidWord: tc.Npc.TidWord, Codename: tc.Npc.Codename, Name: tc.Npc.Name}
		got := BuildNpcCreateRow(npc, tc.Anchor.spawn())
		if !bytes.Equal(got, tc.ExpectedBytes) {
			t.Errorf("createRow gid=%d:\n got % X\nwant % X", tc.Npc.ObjectID, got, tc.ExpectedBytes)
		}
	}

	roster := DefaultNpcRoster()
	for _, tc := range vectors.NpcWire.MovePayloads {
		frames := NpcMoveFrames(roster, tc.Anchor.spawn(), tc.Tick)
		if len(frames) != 1 {
			t.Fatalf("move tick %d: %d frames, want 1", tc.Tick, len(frames))
		}
		if frames[0].Opcode != wire.OpObjectSourceMove {
			t.Errorf("move tick %d: opcode = 0x%04X, want 0x30E3", tc.Tick, frames[0].Opcode)
		}
		if !bytes.Equal(frames[0].Payload, tc.ExpectedBytes) {
			t.Errorf("move tick %d payload:\n got % X\nwant % X", tc.Tick, frames[0].Payload, tc.ExpectedBytes)
		}
	}

	for _, tc := range vectors.NpcWire.CorrectionPayloads {
		frames := NpcCorrectionFrames(roster, tc.Anchor.spawn(), tc.Tick)
		if len(frames) != 1 {
			t.Fatalf("correction tick %d: %d frames, want 1", tc.Tick, len(frames))
		}
		if frames[0].Opcode != wire.OpObjectSourceCorrection {
			t.Errorf("correction tick %d: opcode = 0x%04X, want 0xB2F5", tc.Tick, frames[0].Opcode)
		}
		if !bytes.Equal(frames[0].Payload, tc.ExpectedBytes) {
			t.Errorf("correction tick %d payload:\n got % X\nwant % X", tc.Tick, frames[0].Payload, tc.ExpectedBytes)
		}
	}

	for _, tc := range vectors.NpcWire.StatePayloads {
		frames := NpcMoveStateFrames(roster, tc.Tick)
		if len(frames) != 1 || !bytes.Equal(frames[0].Payload, tc.ExpectedBytes) || frames[0].Opcode != wire.OpObjectStateRefresh {
			t.Errorf("moveState tick %d: got %+v, want payload % X on 0x3122", tc.Tick, frames, tc.ExpectedBytes)
		}
	}

	for _, tc := range vectors.NpcWire.LifePayloads {
		frames := NpcLifeStateFrames(roster, tc.Tick)
		if len(frames) != 1 || !bytes.Equal(frames[0].Payload, tc.ExpectedBytes) || frames[0].Opcode != wire.OpObjectStateRefresh {
			t.Errorf("lifeState tick %d: got %+v, want payload % X on 0x3122", tc.Tick, frames, tc.ExpectedBytes)
		}
	}

	for _, tc := range vectors.NpcWire.DespawnPayloads {
		frames := NpcDespawnFrames(roster)
		if len(frames) <= tc.Index {
			t.Fatalf("despawn: %d frames, want index %d", len(frames), tc.Index)
		}
		frame := frames[tc.Index]
		if frame.Opcode != wire.OpObjectDespawn || !bytes.Equal(frame.Payload, tc.ExpectedBytes) {
			t.Errorf("despawn index %d: got opcode 0x%04X payload % X, want 0x36AB % X", tc.Index, frame.Opcode, frame.Payload, tc.ExpectedBytes)
		}
	}
}

func TestParityGameReady(t *testing.T) {
	vectors := loadParityVectors(t)
	// Calendar constants in the retired Node fixture are not native authority.
	if got := GameTimePayload(); len(got) != 4 || got[2] >= 24 || got[3] >= 60 {
		t.Fatalf("invalid calendar: %v", got)
	}
	for _, tc := range vectors.GameReady.Vitals {
		got := VitalsRefreshPayload(tc.ObjectID, Vitals{CurrentHP: tc.CurrentHP, CurrentMP: tc.CurrentMP})
		if !bytes.Equal(got, tc.ExpectedBytes) {
			t.Errorf("vitals objectId=%d:\n got % X\nwant % X", tc.ObjectID, got, tc.ExpectedBytes)
		}
		frames := GameReadyFrames(tc.ObjectID, Vitals{CurrentHP: tc.CurrentHP, CurrentMP: tc.CurrentMP})
		if len(frames) != 2 || frames[0].Opcode != OpGameTime || frames[1].Opcode != OpVitalsUpdate {
			t.Errorf("gameReady frames: got %+v, want [0x31AD, 0x33A6]", frames)
		}
	}
}
