"""Capture native WideCharToMultiByte(1252, 0) for the web port's ANSI lane.

Run on Windows from apps/server. Native client 4B6960 uses CP_ACP with flags
zero; this port's ANSI decoders select Windows-1252. Do not claim other ACPs.
"""
import ctypes
import hashlib
import json
import platform
from pathlib import Path

k = ctypes.WinDLL('kernel32', use_last_error=True)
f = k.WideCharToMultiByte
f.argtypes = [ctypes.c_uint, ctypes.c_ulong, ctypes.c_wchar_p, ctypes.c_int,
              ctypes.c_void_p, ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p]
f.restype = ctypes.c_int
output = ctypes.create_string_buffer(8)
data = bytearray()
for unit in range(65536):
    n = f(1252, 0, chr(unit), 1, output, 8, None, None)
    if n != 1:
        raise RuntimeError((unit, n, ctypes.get_last_error()))
    data.append(output.raw[0])
# Check every supplementary scalar in bounded batches. With flags zero this
# Windows code page emits one default byte per surrogate, not one per scalar.
supplementary = 0
for start in range(0x10000, 0x110000, 4096):
    text = ''.join(chr(r) for r in range(start, min(start+4096, 0x110000)))
    size = len(text)*2
    buffer = ctypes.create_string_buffer(size)
    n = f(1252, 0, text, size, buffer, size, None, None)
    if n != size or buffer.raw != b'?'*size:
        raise RuntimeError(('supplementary mapping changed', start, n))
    supplementary += len(text)
root = Path('internal/game/item/wire')
fixtures = root / 'testdata'
fixtures.mkdir(exist_ok=True)
(fixtures / 'windows1252.bin').write_bytes(data)
(fixtures / 'windows1252.json').write_text(json.dumps({
    'api': 'WideCharToMultiByte', 'codePage': 1252, 'flags': 0,
    'input': 'each UTF-16 code unit 0..65535, explicit length 1',
    'platform': platform.platform(), 'activeCodePage': k.GetACP(),
    'supplementaryScalarsVerifiedAsTwoDefaultBytes': supplementary,
    'sha256': hashlib.sha256(data).hexdigest(),
}, indent=2) + '\n')
lines = ['// Code generated by ops/tools/capture-windows1252.py; DO NOT EDIT.',
         'package wire', '', 'var windows1252Low = [256]byte{']
for start in range(0, 256, 16):
    lines.append('\t' + ','.join(f'0x{b:02x}' for b in data[start:start+16]) + ',')
lines += ['}', '', 'var windows1252BestFit = map[rune]byte{']
for unit in range(256, 65536):
    if data[unit] != 0x3f:
        lines.append(f'\t0x{unit:04x}: 0x{data[unit]:02x},')
lines += ['}', '']
(root / 'windows1252_data.go').write_text('\n'.join(lines))
print('Captured', len(data), 'UTF-16 code units;', len(lines)-22, 'extended mappings')
