import fs from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildAssetPacks, DEFAULT_ASSET_PACK_TARGET_BYTES } from "./build/assetPacks.mjs";
import { collectAssetPackGroups } from "./build/assetPackGroups.mjs";
import { optimizePublicJsonAssets } from "./build/jsonAssetCompression.mjs";
import { buildWebAssetManifest } from "./build/webManifest.mjs";
import { buildUiImagePreloadManifest } from "./build/uiImagePreload.mjs";
import { copyMissionMinimapTileImages } from "./build/world/assets/copyMissionMinimapTileImages.mjs";
import { withGeneratedAssetsLock } from "./rebuildLock.mjs";

const rebuildRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicRoot = path.join(rebuildRoot, ".generated", "client-public");

await withGeneratedAssetsLock("browser asset pack rebuild", async () => {
const timings = {};
const timed = async (label, task) => {
  const startedAt = performance.now();
  const result = await task();
  timings[label] = `${((performance.now() - startedAt) / 1000).toFixed(1)}s`;
  return result;
};

const uiImagePreload = await timed("uiImagePreload", () => buildUiImagePreloadManifest());
const missionMinimapTiles = await timed("minimapTiles", () => copyMissionMinimapTileImages());

// Packs contain the precompressed JSON sidecars. Refresh them before the
// listing/pack pass so a changed loose manifest cannot be paired with (and
// hidden behind) yesterday's .json.gz bytes. The final pass below remains
// necessary for manifests generated by buildAssetPacks/buildWebAssetManifest.
await timed("jsonOptimization", () => optimizePublicJsonAssets());

// The group list and every sweep/exclusion rule live in build/assetPackGroups.mjs,
// shared with build_sro_resources.mjs so the two entry points cannot drift
// (guarded by scripts/test/assets/assetPackGroupParity.test.mjs).
const packGroups = await timed("listings", () =>
  collectAssetPackGroups({
    uiImagePreloadPaths: uiImagePreload.images.map((image) => image.path),
    missionMinimapTilePaths: missionMinimapTiles.map((tile) => tile.publicPath)
  })
);

const assetPacks = await timed("buildAssetPacks", () =>
  buildAssetPacks({
    targetBytes: DEFAULT_ASSET_PACK_TARGET_BYTES,
    groups: packGroups.groups
  })
);

const missing = [];
for (const group of assetPacks.groups) {
  for (const pack of group.packs) {
    const identityPath = path.join(publicRoot, pack.path.replace(/^\/+/, ""));
    const zstdPath = path.join(publicRoot, (pack.zstdPath ?? `${pack.path}.zst`).replace(/^\/+/, ""));
    // Compact releases deliberately retain zstd-only pack products. The
    // ordinary pack builder can reuse that lossless artifact directly, so the
    // standalone verifier must accept the same identity-or-zstd contract.
    if (!existsSync(identityPath) && !existsSync(zstdPath)) {
      missing.push(pack.path);
    }
  }
}

if (missing.length > 0) {
  throw new Error(`Asset pack manifest references missing pack file(s): ${missing.join(", ")}`);
}

const webManifest = await timed("webManifest", () => buildWebAssetManifest());
// Refresh the precompressed sidecars the regenerated manifests just aged out
// of (the pipeline's finalJsonOptimization step; the freshness rule is
// enforced by generatedAssetMembership.test.mjs).
await timed("finalJsonOptimization", () => optimizePublicJsonAssets());

const summary = Object.fromEntries(
  assetPacks.groups.map((group) => [
    group.name,
    {
      assets: group.assetCount,
      packs: group.packs.map((pack) => pack.path)
    }
  ])
);

console.log(
  JSON.stringify(
    {
      packCount: assetPacks.packCount,
      builtPacks: assetPacks.builtPackCount,
      reusedPacks: assetPacks.reusedPackCount,
      assetCount: assetPacks.assetCount,
      webManifestFileCount: webManifest.files.length,
      webManifestHash: webManifest.manifestHash.slice(0, 12),
      timings,
      summary
    },
    null,
    2
  )
);
});
