import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {withGeneratedAssetsLock} from './rebuildLock.mjs';
import {buildSkillDataAsset} from './build/data/buildSkillDataAsset.mjs';
import {patchAssetPackGroupFromLooseFiles} from './build/sparseAssetPackGroupRefresh.mjs';
import {publishAssetPackManifest} from './build/assetPackPublication.mjs';
import {buildWebAssetManifest} from './build/webManifest.mjs';
import {refreshGeneratedManifestSidecars} from './build/generatedManifestSidecars.mjs';
import {publicRoot} from './build/world/paths.mjs';
await withGeneratedAssetsLock('Native characterInfo publication',async()=>{
 await buildSkillDataAsset();
 const target=path.join(publicRoot,'assets/packs/manifest.json'),previous=JSON.parse(await readFile(target,'utf8'));
 const looseFiles=['/assets/data/skillData.json.gz'],groupName=previous.assets.find(a=>a.path===looseFiles[0])?.group;
 if(!groupName)throw Error('Skill data has no asset-pack owner');
 const update=await patchAssetPackGroupFromLooseFiles({publicRoot,previousIndex:previous,groupName,looseFiles,outputRoot:path.join(publicRoot,'assets/packs/incremental/character-info',groupName)});
 const next={...previous,generatedAt:new Date().toISOString(),groups:[...previous.groups.filter(g=>g.name!==groupName),...update.groups],assets:[...previous.assets.filter(a=>a.group!==groupName),...update.assets].sort((a,b)=>a.path.localeCompare(b.path))};
 if(next.assets.filter(a=>a.path===looseFiles[0]).length!==1)throw Error('CharacterInfo publication closure');
 await publishAssetPackManifest(publicRoot,target,Buffer.from(JSON.stringify(next)),{logLabel:'character-info'});
 await buildWebAssetManifest();await refreshGeneratedManifestSidecars({publicRoot,onlyWhenStale:true});
});
