import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {withGeneratedAssetsLock} from './rebuildLock.mjs';
import {completeRestrictionText} from './build/shared/textResources.mjs';
import {writeJsonIfChanged} from './build/shared/jsonOut.mjs';
import {refreshPrecompressedSidecars,refreshGeneratedManifestSidecars} from './build/generatedManifestSidecars.mjs';
import {patchAssetPackGroupFromLooseFiles} from './build/sparseAssetPackGroupRefresh.mjs';
import {publishAssetPackManifest} from './build/assetPackPublication.mjs';
import {buildWebAssetManifest} from './build/webManifest.mjs';
const root=path.resolve(import.meta.dirname,'..'),publicRoot=path.join(root,'.generated/client-public');
await withGeneratedAssetsLock('Restriction notice English correction',async()=>{
 const target=path.join(publicRoot,'assets/text/textuisystem.en.json'),catalog=JSON.parse(await readFile(target,'utf8'));
 completeRestrictionText(catalog.entries);await writeJsonIfChanged(target,catalog);
 await refreshPrecompressedSidecars([target],{onlyWhenStale:true});
 const manifestPath=path.join(publicRoot,'assets/packs/manifest.json'),previous=JSON.parse(await readFile(manifestPath,'utf8'));
 const looseFiles=['/assets/text/textuisystem.en.json.gz'];
 const groupName=previous.assets.find(a=>a.path===looseFiles[0])?.group;
 if(!groupName)throw Error('UI text has no existing asset-pack ownership');
 const refreshed=await patchAssetPackGroupFromLooseFiles({publicRoot,previousIndex:previous,groupName,looseFiles,outputRoot:path.join(publicRoot,'assets/packs/incremental/restriction-text',groupName)});
 const next={...previous,generatedAt:new Date().toISOString(),groups:[...previous.groups.filter(g=>g.name!==groupName),...refreshed.groups],assets:[...previous.assets.filter(a=>a.group!==groupName),...refreshed.assets].sort((a,b)=>a.path.localeCompare(b.path))};
 if(next.assets.filter(a=>a.path===looseFiles[0]).length!==1)throw Error('Restriction text publication closure');
 await publishAssetPackManifest(publicRoot,manifestPath,Buffer.from(JSON.stringify(next)),{logLabel:'restriction-text'});
 await buildWebAssetManifest();await refreshGeneratedManifestSidecars({publicRoot,onlyWhenStale:true});
 console.log('Refreshed restriction English catalog, compressed sidecars and asset pack.');
});
