export async function probeInventory(page,directory){
 const snapshot=()=>page.evaluate(()=>{const root=globalThis.__worldProbeRoot,g=root.gameplay();return {phase:root.sessionState().phase,items:g.inventory,capacity:g.inventorySlotCount,equipmentSlots:g.equipmentSlotCount,entity:root.entity(g.localGid),pending:g.inventoryPending,error:g.error};});
 const before=await snapshot(),report={before,cycles:[]};await page.keyboard.press('KeyI');
 await page.locator('[data-ui-id="slot:6"]').waitFor({timeout:15000});await page.screenshot({path:directory+'/inventory-before.png'});
 const weapon=before.items.find(i=>i.slot===6)??before.items.find(i=>(i.typeFlags&0x7e)===0x2c&&(i.typeFlags>>>7&15)===6);if(!weapon)throw Error('Scratch inventory needs a weapon');
 const bagSlot=weapon.slot>=before.equipmentSlots?weapon.slot:Array.from({length:before.capacity-before.equipmentSlots},(_,i)=>i+before.equipmentSlots).find(slot=>!before.items.some(i=>i.slot===slot));if(bagSlot===undefined)throw Error('Scratch bag has no free destination');
 async function move(source,destination,targetId=`slot:${destination}`){
  const from=page.locator(`[data-ui-id="slot:${source}"]`),to=page.locator(`[data-ui-id="${targetId}"]`);await from.dragTo(to);
  await page.waitForFunction(({source,destination,ref})=>{const root=globalThis.__worldProbeRoot,g=root.gameplay(),phase=root.sessionState().phase;if(phase!=='world')throw Error('Inventory transition left world: '+phase+' '+document.querySelector('output').textContent);return !g.inventoryPending&&g.inventory.some(i=>i.slot===destination&&i.refObjId===ref)&&!g.inventory.some(i=>i.slot===source);},{source,destination,ref:weapon.refObjId},{timeout:10000});
  report.cycles.push(await snapshot());
 }
 try{if(weapon.slot!==6)await move(bagSlot,6);await page.mouse.move(700,300);await page.waitForTimeout(1200);await page.screenshot({path:directory+'/inventory-equipped.png'});report.rotationControls=await page.evaluate(()=>[...document.querySelectorAll('[data-ui-id^="doll-"]')].map(el=>{const r=el.getBoundingClientRect();return {id:el.dataset.uiId,rect:[r.x,r.y,r.width,r.height],hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.getAttribute('data-ui-id')};}));if(report.rotationControls.some(c=>c.hit!==c.id))throw Error('Inventory semantic label overlaps another control');for(let i=0;i<8;i++)await page.locator('[data-ui-id="doll-right"]').click();await page.mouse.move(700,300);await page.screenshot({path:directory+'/inventory-rotated.png'});await page.locator('[data-ui-id="doll-reset"]').click();for(let i=0;i<2;i++){await move(6,bagSlot);await page.screenshot({path:directory+`/inventory-detached-${i}.png`});await move(bagSlot,6);}await move(6,bagSlot);await move(bagSlot,6,'slot:0');report.autoMatchWrongSocket=true;
 await move(6,bagSlot);
 const source=await page.locator(`[data-ui-id="slot:${bagSlot}"]`).boundingBox();
 await page.mouse.move(source.x+16,source.y+16);await page.mouse.down();await page.mouse.move(700,300,{steps:12});await page.mouse.up();
 await page.locator('[data-ui-id="ground-drop-confirm"]').waitFor({timeout:5000});await page.mouse.move(690,280);await page.screenshot({path:directory+'/inventory-ground-drop-confirm.png'});
 const during=await snapshot();if(!during.items.some(i=>i.slot===bagSlot&&i.refObjId===weapon.refObjId)||during.pending)throw Error('Ground drop sent before confirmation');
 await page.keyboard.press('Escape');await page.locator('[data-ui-id="ground-drop-confirm"]').waitFor({state:'detached'});report.groundDropCancel=true;
 const total=(await snapshot()).items.filter(i=>i.refObjId===weapon.refObjId).reduce((n,i)=>n+i.quantity,0);
 await page.mouse.move(source.x+16,source.y+16);await page.mouse.down();await page.mouse.move(700,300,{steps:12});await page.mouse.up();
 await page.locator('[data-ui-id="ground-drop-confirm"]').waitFor();await page.screenshot({path:directory+'/inventory-ground-drop-confirm.png'});await page.locator('[data-ui-id="ground-drop-confirm"]').click();
 await page.waitForFunction(slot=>{const g=__worldProbeRoot.gameplay();return !g.inventoryPending&&!g.inventory.some(i=>i.slot===slot);},bagSlot,{timeout:10000});report.groundDropped=await snapshot();
 await page.keyboard.down('KeyZ');await page.screenshot({path:directory+'/inventory-ground-dropped.png'});await page.keyboard.up('KeyZ');await page.keyboard.press('KeyG');
 await page.waitForFunction(({ref,total})=>{const g=__worldProbeRoot.gameplay();return !g.inventoryPending&&g.inventory.filter(i=>i.refObjId===ref).reduce((n,i)=>n+i.quantity,0)===total;},{ref:weapon.refObjId,total},{timeout:10000});report.groundPickedUp=true;
 const restored=(await snapshot()).items.find(i=>i.slot===bagSlot&&i.refObjId===weapon.refObjId);if(!restored)throw Error('Picked up row did not return to the vacant bag socket');
 if(weapon.slot===6)await move(bagSlot,6);await page.locator('[data-ui-id="equipment-view"]').click();await page.locator('[data-ui-id="avatar:1"]').waitFor();if(await page.locator('[data-ui-id="slot:6"]').count())throw Error('Normal weapon socket survived avatar view');await page.screenshot({path:directory+'/inventory-avatar.png'});await page.locator('[data-ui-id="equipment-view"]').click();await page.locator('[data-ui-id="slot:6"]').waitFor();await page.locator('[data-ui-id="inventory-gold"]').click();await page.locator('[data-ui-id="gold-amount"]').waitFor();await page.screenshot({path:directory+'/inventory-gold.png'});await page.locator('[data-ui-id="gold-cancel"]').click();
 const current=await snapshot(),stack=current.items.find(i=>i.slot>=current.equipmentSlots&&(i.typeFlags&0x7e)===0x6c&&i.quantity>1&&(i.typeFlags&0xfffe)!==0x7eec),free=Array.from({length:current.capacity-current.equipmentSlots},(_,i)=>i+current.equipmentSlots).find(n=>!current.items.some(i=>i.slot===n));
 if(stack&&free!==undefined&&stack.slot<45&&free<45){
  await page.locator(`[data-ui-id="slot:${stack.slot}"]`).click({modifiers:['Shift']});await page.locator('[data-ui-id="split-amount"]').waitFor();await page.locator('[data-ui-id="split-amount"]').fill('1');await page.screenshot({path:directory+'/inventory-split.png'});await page.locator('[data-ui-id="split-confirm"]').click();
  await page.waitForFunction(({slot,free,ref,count})=>{const g=__worldProbeRoot.gameplay();return !g.inventoryPending&&g.inventory.some(i=>i.slot===free&&i.refObjId===ref&&i.quantity===1)&&g.inventory.some(i=>i.slot===slot&&i.quantity===count-1);},{slot:stack.slot,free,ref:stack.refObjId,count:stack.quantity},{timeout:10000});
  report.split=await snapshot();await page.locator(`[data-ui-id="slot:${free}"]`).dragTo(page.locator(`[data-ui-id="slot:${stack.slot}"]`));
  await page.waitForFunction(({slot,free,count})=>{const g=__worldProbeRoot.gameplay();return !g.inventoryPending&&!g.inventory.some(i=>i.slot===free)&&g.inventory.some(i=>i.slot===slot&&i.quantity===count);},{slot:stack.slot,free,count:stack.quantity},{timeout:10000});report.splitRestored=true;
 }else report.splitSkipped='No splittable stack and free slot on first bag page';
 report.after=await snapshot();report.pass=true;return report;}
 finally{await (await import('node:fs/promises')).writeFile(directory+'/inventory.json',JSON.stringify(report,null,2));}
}
